region: 'eu-west-1'
stack_name: GenericEMRStack
networking_stack_name: NetworkingStack
core_instances: '2'
version: emr-5.8.0
ssh_key: nicor88-dev
applications:
  - Ganglia
  - Hadoop
  - Hive
  - Presto
  - Spark
