stack_name: 'StreamToS3-Stack'
region: 'eu-west-1'

s3_destination_bucket: 'nicor-data'
s3_deployment_bucket: 'nicor-dev'

kinesis_stream_name: 'DevStreamS3'
kinesis_shard_count: 2
kinesis_delivery_stream_name: 'DevDeliveryStreamS3'
firehose_interval_secs: 60
firehose_buffer_mb: 5
firehose_compression_format: UNCOMPRESSED

lambda_function_name: 'kinesis_to_firehose_s3'
s3_key_lambda: 'deployments/lambdas/travis_build/deliver_to_firehose.zip'
lambda_batch_size: 100
lambda_memory_size: 128
lambda_timeout: 30
lambda_enabled: True
lambda_starting_position: LATEST
# if multiple lambdas are reading from the stream consider to use LATEST
